### ISSUE TITLE
'Octopress new' broken in 3.0.1: missing config key

### ISSUE THREAD

**Issue by Billiam** [octopress/octopress#104]
Octopress is expecting a `source` key in the jekyl config, which is not present on initialization. 

User receives error as follows:

```
$ bundle exec octopress new blog -t
New jekyll site installed in path.to/Blog/blog.
ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/lib/octopress/scaffold.rb:21:in `join': no implicit conversion of nil into String (TypeError)
        from ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/lib/octopress/scaffold.rb:21:in `init_path'
        from ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/lib/octopress/scaffold.rb:8:in `initialize'
        from ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/lib/octopress/commands/new.rb:16:in `new'
        from ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/lib/octopress/commands/new.rb:16:in `block (2 levels) in init_with_program'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from ruby/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from ruby/lib/ruby/gems/2.2.0/gems/octopress-3.0.1/bin/octopress:10:in `<top (required)>'
        from ruby/bin/octopress:23:in `load'
        from ruby/bin/octopress:23:in `<main>'
```

**Comment by imathis** [comment]
Thanks for the report. I've just released a fix!
