### ISSUE TITLE
Another dependency error?

### ISSUE THREAD

**Issue by hseeberger** [octopress/octopress#107]
Using the latest and greatest Octopress 3.0.5 I get:

```
hseeberger.github.io$ jekyll serve
Configuration file: /Users/heiko/projects/ghpages/hseeberger.github.io/_config.yml
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.0, ~> 3.1)
      fast-stemmer (~> 1.0)
      octopress-linkblog (>= 0)
      octopress-hooks (~> 2.0, ~> 2.2)
      octopress-autoprefixer (~> 1.0)
      octopress-tag-helpers (~> 1.0)
      octopress-include-tag (~> 1.0)
      octopress-social (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.2.0/gems/octopress-ink-1.1.1/lib/octopress-ink.rb:6:in `require': cannot load such file -- octopress-hooks (LoadError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/octopress-ink-1.1.1/lib/octopress-ink.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/octopress-genesis-theme-0.0.10/lib/octopress-genesis-theme.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by imathis** [comment]
I still haven't been able to release the latest Octopress Ink with wider support for older and newer versions of Jekyll. I believe that will address this.

**Comment by hseeberger** [comment]
Sorry for being pushy ;-)

**Comment by imathis** [comment]
No worries. it's just tricker than I thought to get this released. I'm trying to make this release work with Jekyll 2.x -> 3.x but Octopress Ink depends on several other gems which have a Jekyll 2.5 minimum. I'm having to update them all, test them, and make changes as necessary. Also some changes in Jekyll 3 (I think it's the new Liquid stuff) seem to break some dependencies so I'm trying to fix those too.

**Comment by imathis** [comment]
I belive I've fixed all of these and released all gems that would cause this issue. Please run bundle update and see if that works for you again. Thanks :)

**Comment by hseeberger** [comment]
Thanks!

`jekyll serve` works now. Well, I get the following warning, but it works:

```
hseeberger.github.io$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      fast-stemmer (~> 1.0)
WARN: Clearing out unresolved specs.
...
```

**Comment by imathis** [comment]
Try `bundle exec jekyll serve`

**Comment by hseeberger** [comment]
Nice! That helps. Thanks.
