### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by hotfix** [octopress/octopress#136]
Hi,
I'm trying to add plug-ins to my octopress

so i add in to my _config.yml this lines
```
gems:
  - octopress-codeblock
  - octopress-codefence
  - octopress-genesis-theme
```

after i tried to build the project and get error like  "Object doesn't support this property or method"

```

D:\projekte\hotfix.github.io>jekyll build -t
Configuration file: D:/projekte/hotfix.github.io/_config.yml
            Source: D:/projekte/hotfix.github.io
       Destination: D:/projekte/hotfix.github.io/_site
      Generating...
E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:39:in `exec': TypeError: Das Objekt unterstutzt diese Eigenschaft oder Methode nicht. (ExecJS::ProgramError)
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:14:in `initialize'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `new'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/runtime.rb:44:in `compile'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/execjs-2.5.2/lib/execjs/module.rb:27:in `compile'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails/processor.rb:31:in `processor'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails/processor.rb:20:in `process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/autoprefixer-rails-2.2.0.20140804/lib/autoprefixer-rails.rb:10:in `process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:37:in `block in prefix'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:36:in `open'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:36:in `prefix'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:30:in `block in process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:29:in `each'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:29:in `process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-autoprefixer-1.0.1/lib/octopress-autoprefixer.rb:18:in `post_write'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:223:in `block in write'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `each'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:222:in `write'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:53:in `process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from E:/Programme/Ruby22/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from E:/Programme/Ruby22/bin/jekyll:23:in `load'
        from E:/Programme/Ruby22/bin/jekyll:23:in `<main>'

```

I'm using windows7, looks like a problem with execjs library?

Thanks Alex

**Comment by gregoryjscott** [comment]
@hotfix Just ran into this exact error and it was due not having a JavaScript runtime installed. (In my case it was a Windows CI server.) Read https://github.com/sstephenson/execjs for JavaScript runtime options (e.g. Node).

**Comment by hotfix** [comment]
@gregoryjscott  thanks works for me too.
