### ISSUE TITLE
Cannot unpublish a post

### ISSUE THREAD

**Issue by abustamam** [octopress/octopress#137]
Tried to unpublish a post, got this error:

```
/Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress/post.rb:53:in `unpublish': cannot load such file -- octopress/draft (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress/commands/unpublish.rb:28:in `unpublish_post'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/lib/octopress/commands/unpublish.rb:18:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
	from /usr/bin/octopress:23:in `load'
	from /usr/bin/octopress:23:in `<main>'
```

I wonder if `octopress/draft` should be `octopress/drafts`?

**Comment by abustamam** [comment]
Nevermind. I updated octopress to the latest, and it works.
