### ISSUE TITLE
Octopress crashes with latest gems

### ISSUE THREAD

**Issue by justin808** [octopress/octopress#152]
I just ran bundle update given the following Gemfile, and prior/next Gemfile.lock. Some changes in peer dependencies breaks Octopress.

```
octopress docs                                                                                                                                                                                                    ✹ [13:39:32]
/Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:140: warning: already initialized constant Jekyll::PageHooks
/Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:140: warning: previous definition of PageHooks was here
/Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:320:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:136:in `<top (required)>'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-3.0.11/lib/octopress/docs.rb:222:in `require'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-3.0.11/lib/octopress/docs.rb:222:in `load_docs'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:25:in `serve_docs'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:16:in `block (2 levels) in init_with_program'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/justin/.rvm/gems/ruby-2.2.3@rails42/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
	from /Users/justin/shakacode/shakacode-website/bin/octopress:16:in `load'
```

Gemfile:
```
source 'https://rubygems.org'

gem 'octopress', '~> 3.0'
group :jekyll_plugins do
  gem 'octopress-asset-pipeline'
end
```

New Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    autoprefixer-rails (2.2.0.20140804)
      execjs
    colorator (0.1)
    execjs (2.6.0)
    ffi (1.9.10)
    jekyll (3.0.0)
      colorator (~> 0.1)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.3.0)
      listen (~> 3.0)
    json (1.8.3)
    kramdown (1.9.0)
    liquid (3.0.6)
    listen (3.0.4)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    octopress (3.0.11)
      jekyll (>= 2.0)
      mercenary (~> 0.3.2)
      octopress-deploy
      octopress-escape-code (~> 2.0)
      octopress-hooks (~> 2.0)
      redcarpet (~> 3.0)
      titlecase
    octopress-asset-pipeline (2.0.6)
      octopress-ink (~> 1.1.0)
    octopress-autoprefixer (1.0.1)
      autoprefixer-rails (~> 2.2)
      jekyll (>= 2.0)
      octopress-hooks (~> 2.0)
    octopress-date-format (3.0.3)
      jekyll (>= 2.0)
    octopress-deploy (1.3.0)
      colorator
    octopress-escape-code (2.0.6)
      octopress-hooks (~> 2.0)
    octopress-filters (1.4.0)
      jekyll
      octopress-hooks (~> 2.0)
      rubypants-unicode
      titlecase
    octopress-hooks (2.6.1)
      jekyll (>= 2.0)
    octopress-include-tag (1.1.3)
      jekyll (>= 2.0)
      octopress-tag-helpers (~> 1.0)
    octopress-ink (1.1.4)
      jekyll (>= 2.0)
      octopress (~> 3.0)
      octopress-autoprefixer
      octopress-date-format
      octopress-filters (~> 1.1)
      octopress-hooks (~> 2.2)
      octopress-include-tag (~> 1.0)
      uglifier (~> 2.5)
    octopress-tag-helpers (1.0.8)
      jekyll (>= 2.0)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.3.3)
    rouge (1.10.1)
    rubypants-unicode (0.2.5)
    safe_yaml (1.0.4)
    sass (3.4.19)
    titlecase (0.1.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)

PLATFORMS
  ruby

DEPENDENCIES
  octopress (~> 3.0)
  octopress-asset-pipeline

BUNDLED WITH
   1.10.6
```

Old Gemfile:

```
source 'https://rubygems.org'

gem 'jekyll'
group :jekyll_plugins do
  gem 'octopress-asset-pipeline'
end
```

Old Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    autoprefixer-rails (2.2.0.20140804)
      execjs
    blankslate (2.1.2.4)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    classifier-reborn (2.0.3)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorator (0.1)
    execjs (2.6.0)
    fast-stemmer (1.0.2)
    ffi (1.9.10)
    hitimes (1.2.3)
    jekyll (2.5.3)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-gist (1.3.4)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.2.1)
      listen (~> 2.7)
    json (1.8.3)
    kramdown (1.8.0)
    liquid (2.6.3)
    listen (2.10.1)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    octopress (3.0.11)
      jekyll (>= 2.0)
      mercenary (~> 0.3.2)
      octopress-deploy
      octopress-escape-code (~> 2.0)
      octopress-hooks (~> 2.0)
      redcarpet (~> 3.0)
      titlecase
    octopress-asset-pipeline (2.0.6)
      octopress-ink (~> 1.1.0)
    octopress-autoprefixer (1.0.1)
      autoprefixer-rails (~> 2.2)
      jekyll (>= 2.0)
      octopress-hooks (~> 2.0)
    octopress-date-format (3.0.3)
      jekyll (>= 2.0)
    octopress-deploy (1.3.0)
      colorator
    octopress-escape-code (2.0.6)
      octopress-hooks (~> 2.0)
    octopress-filters (1.4.0)
      jekyll
      octopress-hooks (~> 2.0)
      rubypants-unicode
      titlecase
    octopress-hooks (2.6.1)
      jekyll (>= 2.0)
    octopress-include-tag (1.1.3)
      jekyll (>= 2.0)
      octopress-tag-helpers (~> 1.0)
    octopress-ink (1.1.4)
      jekyll (>= 2.0)
      octopress (~> 3.0)
      octopress-autoprefixer
      octopress-date-format
      octopress-filters (~> 1.1)
      octopress-hooks (~> 2.2)
      octopress-include-tag (~> 1.0)
      uglifier (~> 2.5)
    octopress-tag-helpers (1.0.8)
      jekyll (>= 2.0)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.11)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.3.2)
    rubypants-unicode (0.2.5)
    safe_yaml (1.0.4)
    sass (3.4.18)
    timers (4.0.4)
      hitimes
    titlecase (0.1.1)
    toml (0.1.2)
      parslet (~> 1.5.0)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  octopress-asset-pipeline

BUNDLED WITH
   1.10.6
```

**Comment by justin808** [comment]
Here's the Gemfile that works: 

https://gist.github.com/justin808/57dbd295ce9fe3a72fde

```
source "https://rubygems.org"

gem "octopress", "~>3"
gem "jekyll", "<3"
group :jekyll_plugins do
  gem "octopress-asset-pipeline"
end
```
