### ISSUE TITLE
octopress docs `Liquid Exception`

### ISSUE THREAD

**Issue by jaykilleen** [octopress/octopress#158]
Hi 

Heard you on the Changelog podcast and am giving Octopress a whirl (would love to get off Wordpress).

I am slowly getting through it but think I may have come across a bug when trying to access the docs from Ubuntu 14.04 Virtualbox (Windows 10 Host).

```
jay@jay-ubuntu-vb:/media/sf_app/jaykilleen.github.io$ octopress docs
  Liquid Exception: no implicit conversion of nil into String in index.html
octopress 3.0.11 | Error:  no implicit conversion of nil into String
```

Let me know if you need more info.

**Comment by onebree** [comment]
I installed the octopress gem for the first time, latest version, and got the same error.

```
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
      redcarpet (~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
  Liquid Exception: no implicit conversion of nil into String in index.html
octopress 3.0.11 | Error:  no implicit conversion of nil into String
```

**Comment by anatol** [comment]
I ran `octopress init; octopress docs` and get the same error:

```
$ octopress docs --trace
  Liquid Exception: no implicit conversion of nil into String in index.html
/usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll.rb:156:in `expand_path': no implicit conversion of nil into String (TypeError)
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll.rb:156:in `sanitized_path'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:355:in `block in in_source_dir'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:354:in `each'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:354:in `reduce'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:354:in `in_source_dir'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/liquid_renderer.rb:16:in `file'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/renderer.rb:106:in `render_liquid'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:311:in `render_liquid'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/renderer.rb:61:in `run'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:306:in `run'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:179:in `block in render'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:177:in `each'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:177:in `render'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/site.rb:59:in `process'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/command.rb:26:in `process_site'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/commands/build.rb:60:in `build'
    from /usr/lib/ruby/gems/2.3.0/gems/jekyll-3.1.1/lib/jekyll/commands/build.rb:33:in `process'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:33:in `serve_docs'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:16:in `block (2 levels) in init_with_program'
    from /usr/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /usr/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /usr/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /usr/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /usr/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /usr/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
    from /usr/bin/octopress:23:in `load'
    from /usr/bin/octopress:23:in `<main>'
```

**Comment by TheLonelyGhost** [comment]
Odd... I get a different stack trace with Ruby 2.3.0 and Octopress 3.0.11. I've also confirmed the same issue in Ruby 2.2.3. Perhaps this means it's an issue with Jekyll?

``` bash
$ octopress new .; octopress deploy init git "$git_url" --branch master
# [snip]
$ octopress docs
  Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
/Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll.rb:156:in `sanitized_path': undefined method `start_with?' for nil:NilClass (NoMethodError)
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:355:in `block in in_source_dir'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:354:in `each'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:354:in `reduce'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:354:in `in_source_dir'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer.rb:16:in `file'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:106:in `render_liquid'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:311:in `render_liquid'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:61:in `run'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:306:in `run'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:179:in `block in render'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `each'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `render'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:59:in `process'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/command.rb:26:in `process_site'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:60:in `build'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:33:in `process'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:33:in `serve_docs'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:16:in `block (2 levels) in init_with_program'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /Users/dpalexander/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
        from /Users/dpalexander/.rbenv/versions/2.3.0/bin/octopress:23:in `load'
        from /Users/dpalexander/.rbenv/versions/2.3.0/bin/octopress:23:in `<main>'
```

**Comment by resurrexit** [comment]
Anyone else still getting this? Using Octopress 3.0.11 and Ruby 2.2.5, with Jekyll 3.1.6.

```
/home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll.rb:154:in `sanitized_path': undefined method `start_with?' for nil:NilClass (NoMethodError)
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:356:in `block in in_source_dir'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:355:in `each'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:355:in `reduce'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:355:in `in_source_dir'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer.rb:16:in `file'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:106:in `render_liquid'
    from /home/resurrexit/.gem/ruby/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:311:in `render_liquid'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:61:in `run'
    from /home/resurrexit/.gem/ruby/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:306:in `run'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:179:in `block in render'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `each'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `render'
    from /home/resurrexit/.gem/ruby/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/site.rb:59:in `process'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/command.rb:26:in `process_site'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:60:in `build'
    from /home/resurrexit/.gem/ruby/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:33:in `process'
    from /home/resurrexit/.gem/ruby/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:33:in `serve_docs'
    from /home/resurrexit/.gem/ruby/gems/octopress-3.0.11/lib/octopress/commands/docs.rb:16:in `block (2 levels) in init_with_program'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
    from /home/resurrexit/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
    from /home/resurrexit/.gem/ruby/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
    from /home/resurrexit/bin/octopress:23:in `load'
    from /home/resurrexit/bin/octopress:23:in `<main>'
```

**Comment by randycoulman** [comment]
Yes, this still happens, but seems to be fixed by an unreleased commit: https://github.com/octopress/octopress/commit/4e855049f8f989acc3d24d73347d5671cf82a83d

Unfortunately, that just leads to a new error (I don't have it in front of me), but at least it gets you further down the road.

**Comment by nicluo** [comment]
Can confirm `octopress docs` works for me correctly on Jekyll 2.5.3

On my other computer with Jekyll 3.1.6, I got this instead:

```
$ octopress docs
Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
octopress 3.0.11 | Error:  undefined method `start_with?' for nil:NilClass
```

**Comment by ayashjorden** [comment]
+1

```
$ octopress bundle exec octopress docs
  Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
octopress 3.0.11 | Error:  undefined method `start_with?' for nil:NilClass
```

Any update?

**Comment by marcamillion** [comment]
Any update on this? Here are my versions:

```
$ jekyll --v
jekyll 3.2.1
$ octopress --v
octopress 3.0.11
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ octopress docs
  Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
octopress 3.0.11 | Error:  undefined method `start_with?' for nil:NilClass
$ bundle exec octopress docs
  Liquid Exception: undefined method `start_with?' for nil:NilClass in index.html
octopress 3.0.11 | Error:  undefined method `start_with?' for nil:NilClass
```
