### ISSUE TITLE
Cancelling `octopress isolate` results in an error

### ISSUE THREAD

**Issue by dgmstuart** [octopress/octopress#161]
When trying to isolate a file I'm editing, I get an option of isolating the saved file or the swapfile. There isn't an option to cancel, so I hit Ctrl-C to exit, which results in the error below.

I'd expect this to exit sliently.

```
» bundle exec octopress isolate inline
Found 2 posts matching: 'inline'
  1) .2015-03-27-execute-ruby-code-inline-in-the-editor.markdown.swp
  2) 2015-03-27-execute-ruby-code-inline-in-the-editor.markdown
Which do you want to isolate? (enter a number): ^C/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octopress-3.0.11/lib/octopress/commands/helpers.rb:80:in `gets': Interrupt
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octopress-3.0.11/lib/octopress/commands/helpers.rb:80:in `prompt_for_selection'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octopress-3.0.11/lib/octopress/commands/helpers.rb:20:in `select_posts'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octopress-3.0.11/lib/octopress/commands/isolate.rb:14:in `block (2 levels) in init_with_program'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.2.3/bin/octopress:23:in `load'
    from /usr/local/var/rbenv/versions/2.2.3/bin/octopress:23:in `<main>'
```

**Comment by jeremyz** [comment]
SIGINT signal is not trapped, thus it kills the process which is what you wanted to do.
just hit enter to end it nicely ;)
