### ISSUE TITLE
Rake generate not working

### ISSUE THREAD

**Issue by 1217110883** [octopress/octopress#183]
I get the following error when I do` rake generate`

```
Starting to watch source with Jekyll and Compass. Starting Rack on port 4000
directory source/stylesheets
DEPRECATION WARNING on line 87 of /var/lib/gems/2.3.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('"$moz-"#{$experimental-support-for-mozilla} "$webkit-"#{$experimental-support-for-webkit} "$opera-"#{$experimental-support-for-opera} "$microsoft-"#{$experimental-support-for-microsoft} "$khtml-"#{$experimental-support-for-khtml}')

You can use the sass-convert command to automatically fix most cases.

DEPRECATION WARNING on line 92 of /var/lib/gems/2.3.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote('"$ie6-"#{$legacy-support-for-ie6} "$ie7-"#{$legacy-support-for-ie7} "$ie8-"#{$legacy-support-for-ie8}')

You can use the sass-convert command to automatically fix most cases.

    write source/stylesheets/screen.css
[2017-03-08 16:38:02] INFO  WEBrick 1.3.1
[2017-03-08 16:38:02] INFO  ruby 2.3.1 (2016-04-26) [i386-linux-gnu]
[2017-03-08 16:38:02] INFO  WEBrick::HTTPServer#start: pid=11564 port=4000
>>> Compass is watching for changes. Press Ctrl-C to Stop.
directory public/stylesheets
Configuration file: /home/ubuntu/octopress/_config.yml
/var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix/spawn.rb:2:in `require': /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix_spawn_ext.so: undefined symbol: rb_fix2int - /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix_spawn_ext.so (LoadError)
	from /var/lib/gems/2.3.0/gems/posix-spawn-0.3.13/lib/posix/spawn.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:2:in `require'
	from /var/lib/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `require'
	from /var/lib/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments.rb:1:in `<top (required)>'
	from /home/ubuntu/octopress/plugins/pygments_code.rb:1:in `require'
	from /home/ubuntu/octopress/plugins/pygments_code.rb:1:in `<top (required)>'
	from /home/ubuntu/octopress/plugins/backtick_code_block.rb:1:in `require'
	from /home/ubuntu/octopress/plugins/backtick_code_block.rb:1:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:74:in `block (2 levels) in require_plugin_files'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:72:in `require_plugin_files'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.3.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
    write public/stylesheets/screen.css
```

**Comment by P3lUZa** [comment]
Im having the same problem :(

**Comment by P3lUZa** [comment]
Its a problem realted to posix_spawn 0.13 , the solution is to use the old version 0.3.12 instead.
Solved!
