### ISSUE TITLE
FrozenError when using octopress publish 

### ISSUE THREAD

**Issue by sulibo** [octopress/octopress#186]
I got a FrozenError when using `octopress publish` to publish a draft. I am using Ruby 2.7 on macOS. Any suggestion to solve this issue? Thanks in advance!

```ruby 
octopress 3.0.11 | Error:  can't modify frozen String: ""
Traceback (most recent call last):
	17: from /usr/local/bin/octopress:23:in `<main>'
	16: from /usr/local/bin/octopress:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/bin/octopress:8:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/commands/publish.rb:22:in `block (2 levels) in init_with_program'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/commands/publish.rb:32:in `publish_post'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/commands/publish.rb:32:in `new'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/page.rb:30:in `initialize'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/page.rb:136:in `content'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/octopress-3.0.11/lib/octopress/page.rb:155:in `parse_template'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/titlecase-0.1.1/lib/titlecase.rb:19:in `titlecase!'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/titlecase-0.1.1/lib/titlecase.rb:12:in `titlecase'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/titlecase-0.1.1/lib/titlecase.rb:34:in `smart_capitalize!'
/usr/local/lib/ruby/gems/2.7.0/gems/titlecase-0.1.1/lib/titlecase.rb:34:in `replace': can't modify frozen String: "" (FrozenError)
```

**Comment by garrettlancaster** [comment]
There seems to be a bug where the title is not loaded from the template prior to attempting to titlecase! @options[title] in page.rb

I added a rescue to that line (155) to get around it
