### ISSUE TITLE
"octopress new post" failing to generate slug with non ASCII titles on Windows

### ISSUE THREAD

**Issue by hazzik** [octopress/octopress#44]
Intro: I'm Russian and I want to write posts in Russian, but I can not use octopress 3.0 to create files from command line. Also I'm using Ruby 2.0 x64 on Windows 7 x64

I tried to set encoding of command promt to be 'windows-1251' and 65001 (utf-8) with `chcp`, but that did not help:

```text
> bundle exec octopress new post "тест"
octopress 3.0.0.rc.12 | Error:  incompatible encoding regexp match (UTF-8 regexp with IBM866 string)
> chcp 1251
> bundle exec octopress new post "тест"
octopress 3.0.0.rc.12 | Error:  incompatible encoding regexp match (UTF-8 regexp with Windows-1251 string)
> chcp 65001
> bundle exec octopress new post "тест"
DL is deprecated, please use Fiddle
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/parser/arguments.rb:12:in `block in split': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/parser/arguments.rb:11:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/parser/arguments.rb:11:in `split'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:344:in `dispatch'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in `start'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
        from C:/Ruby200-x64/bin/bundle:23:in `load'
        from C:/Ruby200-x64/bin/bundle:23:in `<main>'
```

**Comment by imathis** [comment]
I'm going to assume this has been settled. If not, I'm happy to reopen it.

**Comment by hazzik** [comment]
Still happens in Windows machine with fresh untouched octopress, but as I said before - I use StringEx#to_url to generate slugs, so does not really matter for me.
