### ISSUE TITLE
Error when creating scaffolding

### ISSUE THREAD

**Issue by kumpelblase2** [octopress/octopress#93]
I receive the following error when I run `octopress init testing` :
```
$ octopress init testing
/Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.0.rc.34/lib/octopress/command.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.0.rc.34/lib/octopress.rb:7:in `<module:Octopress>'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.0.rc.34/lib/octopress.rb:4:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/octopress-3.0.0.rc.34/bin/octopress:6:in `<top (required)>'
	from /usr/bin/octopress:23:in `load'
	from /usr/bin/octopress:23:in `<main>'
```

Running 3.0.0.rc.34 on OSX 10.10.2 with Ruby 2.0.0p481
This was pretty much the first thing I did after the installation finished. Installation log:
```
$ gem install octopress --pre
Fetching: octopress-escape-code-2.0.6.gem (100%)
Successfully installed octopress-escape-code-2.0.6
Fetching: octopress-deploy-1.1.0.gem (100%)
Successfully installed octopress-deploy-1.1.0
Fetching: titlecase-0.1.1.gem (100%)
Successfully installed titlecase-0.1.1
Fetching: octopress-3.0.0.rc.34.gem (100%)
Successfully installed octopress-3.0.0.rc.34
Parsing documentation for octopress-escape-code-2.0.6
Installing ri documentation for octopress-escape-code-2.0.6
Parsing documentation for octopress-deploy-1.1.0
Installing ri documentation for octopress-deploy-1.1.0
Parsing documentation for titlecase-0.1.1
Installing ri documentation for titlecase-0.1.1
Parsing documentation for octopress-3.0.0.rc.34
Installing ri documentation for octopress-3.0.0.rc.34
Done installing documentation for octopress-escape-code, octopress-deploy, titlecase, octopress after 0 seconds
4 gems installed
```

Do I need to install a missing dependency or am I missing something else?
Kind regards

**Comment by imathis** [comment]
Hmm. This is curious. Any clue about this one @parkr?

**Comment by kumpelblase2** [comment]
Ok, I just updated psych to 2.0.13 and it's working now.

**Comment by imathis** [comment]
Goody, that's an odd issue. I'm not explicitly requiring psych. Perhaps SafeYAML has a lax dependency setting.
