### ISSUE TITLE
Error: cannot load such file -- jekyll-sitemap

### ISSUE THREAD

**Issue by ilya-murzinov** [octopress/octopress#96]
I have the following error with the version 3.0.0.rc.34
```
$ octopress new post 'Awesome post!'
/home/action/.gem/ruby/2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
	from /home/action/.gem/ruby/2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /home/action/.gem/ruby/2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /home/action/.gem/ruby/2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /home/action/.gem/ruby/2.1.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /home/action/.gem/ruby/2.1.1/gems/octopress-3.0.0.rc.34/lib/octopress.rb:69:in `read_site'
	from /home/action/.gem/ruby/2.1.1/gems/octopress-3.0.0.rc.34/lib/octopress.rb:60:in `site'
	from /home/action/.gem/ruby/2.1.1/gems/octopress-3.0.0.rc.34/lib/octopress/commands/new.rb:52:in `block (3 levels) in init_with_program'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/action/.gem/ruby/2.1.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/action/.gem/ruby/2.1.1/gems/octopress-3.0.0.rc.34/bin/octopress:16:in `<top (required)>'
	from /home/action/.gem/ruby/2.1.1/bin/octopress:23:in `load'
	from /home/action/.gem/ruby/2.1.1/bin/octopress:23:in `<main>'
```
Environment:
```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.1 (2014-02-24 patchlevel 76) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/action/.gem/ruby/2.1.1
  - RUBY EXECUTABLE: /home/action/.parts/packages/ruby2.1/2.1.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/action/.gem/ruby/2.1.1/bin
  - SPEC CACHE DIRECTORY: /home/action/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/action/.gem/ruby/2.1.1
     - /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/gems/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/action/.gem/ruby/2.1.1/bin
     - /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/gems/2.1.0/bin
     - /home/action/.parts/opt/rubies/ruby-2.1.1/bin
     - /home/action/.parts/bin
     - /home/action/.parts/sbin
     - /home/action/.parts/autoparts/bin
     - /home/action/.parts/autoparts/bin
     - /home/action/.parts/autoparts/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /home/action/.gem/ruby/1.9.1/bin
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.1 (2014-02-24 patchlevel 76) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/action/.gem/ruby/2.1.1
  - RUBY EXECUTABLE: /home/action/.parts/packages/ruby2.1/2.1.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/action/.gem/ruby/2.1.1/bin
  - SPEC CACHE DIRECTORY: /home/action/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/action/.gem/ruby/2.1.1
     - /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/gems/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/action/.gem/ruby/2.1.1/bin
     - /home/action/.parts/packages/ruby2.1/2.1.1/lib/ruby/gems/2.1.0/bin
     - /home/action/.parts/opt/rubies/ruby-2.1.1/bin
     - /home/action/.parts/bin
     - /home/action/.parts/sbin
     - /home/action/.parts/autoparts/bin
     - /home/action/.parts/autoparts/bin
     - /home/action/.parts/autoparts/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /home/action/.gem/ruby/1.9.1/bin
```

**Comment by ilya-murzinov** [comment]
And also
```
$ bundle install
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1
Using execjs 2.3.0
Using coffee-script 2.3.0
Using colorator 0.1
Using ffi 1.9.6
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.1.0
Using jekyll-paginate 1.1.0
Using sass 3.4.12
Using jekyll-sass-converter 1.3.0
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using jekyll-watch 1.2.1
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.5
Using posix-spawn 0.3.10
Using yajl-ruby 1.2.1
Using pygments.rb 0.6.2
Using redcarpet 3.2.2
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.5.3
Using jekyll-sitemap 0.8.0
Using octopress-deploy 1.1.0
Using octopress-hooks 2.6.0
Using octopress-escape-code 2.0.6
Using titlecase 0.1.1
Using octopress 3.0.0.rc.34
Using rouge 1.8.0
Using bundler 1.6.2
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by parkr** [comment]
Try `bundle exec octopress new post ...` or remove `jekyll-sitemap` from your gemfile and/or your `_config.yml`.

**Comment by ilya-murzinov** [comment]
Yep, it works.
Thank you for the quick response!
